routes:

collections:
  /enterprise/:
    permalink: /enterprise/{slug}/
    filter: tag:hash-enterprise
    template: tag-enterprise
  /franquicias/:
    permalink: /franquicias/{slug}/
    filter: tag:hash-franquicias
    template: tag-franquicias
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
